name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  folder_introduccion:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
    - name: Ejecutar script introducción
      run: |
        cd Introducción
        gcc principal.c -o introduccion
        ./introduccion
